import type { EnvVariable } from "@/types/analysis";

/**
 * Pure function: generate Markdown documentation for variables.
 */
export function generateDocumentation(variables: EnvVariable[]): string {
  const vars = variables.filter((v) => !v.exampleOnly);
  const lines: string[] = [
    "# Environment Variables",
    "",
    "Generated by EnvSmith.",
    "",
    "| Variable | Type | Required | Secret | Description |",
    "| --- | --- | --- | --- | --- |",
  ];

  for (const v of vars) {
    const type = v.type.charAt(0).toUpperCase() + v.type.slice(1);
    const required = v.required && v.rawValue !== "" ? "Yes" : "No";
    const secret =
      v.classification === "secret" ? "Yes" : v.classification === "likely-secret" ? "Likely" : "No";
    const description = (v.description || "—").replace(/\|/g, "\\|").replace(/\n/g, " ");
    lines.push(`| \`${v.key}\` | ${type} | ${required} | ${secret} | ${description} |`);
  }

  return `${lines.join("\n")}\n`;
}
