import type { EnvVariable } from "@/types/analysis";
import { isSecretLike } from "./utils";

export type SchemaTarget = "zod" | "ts-types" | "json-schema" | "dotenv-validation";

export interface ZodGenerationOptions {
  target: SchemaTarget;
}

/**
 * Pure function: generate a production-friendly runtime validation schema.
 * process.env values are strings, so we coerce numbers/booleans.
 */
export function generateZodSchema(variables: EnvVariable[], options: ZodGenerationOptions): string {
  const vars = variables.filter((v) => !v.exampleOnly);
  if (options.target === "ts-types") return generateTsTypes(vars);
  if (options.target === "json-schema") return generateJsonSchema(vars);
  if (options.target === "dotenv-validation") return generateDotenvValidation(vars);
  return generateZod(vars);
}

function zodRuleFor(v: EnvVariable): string {
  const isRequired = v.required && v.rawValue !== "";
  const hasDefault = !v.required && v.rawValue !== "" && !isSecretLike(v);
  const treatAsSecret = v.classification === "secret" || v.classification === "likely-secret";

  const stringPart = v.type === "url" ? "z.string().url()" : "z.string()";
  let rule: string;

  switch (v.type) {
    case "number": {
      const int = Number.isInteger(Number(v.rawValue));
      const positive = v.rawValue !== "" && Number(v.rawValue) > 0;
      let chain = "z.coerce.number()";
      if (int) chain += ".int()";
      if (positive) chain += ".positive()";
      rule = chain;
      break;
    }
    case "boolean": {
      // process.env booleans are strings; accept the common string forms safely
      rule = 'z.enum(["true", "false"]).transform((v) => v === "true")';
      break;
    }
    case "url":
      rule = "z.string().url()";
      break;
    case "json":
      rule =
        'z.string().transform((v, ctx) => { try { return JSON.parse(v); } catch { ctx.addIssue({ code: "custom", message: "Invalid JSON" }); return z.NEVER; } })';
      break;
    default:
      rule = treatAsSecret ? `${stringPart}.min(1)` : stringPart;
  }
  if (v.type === "json" && hasDefault) {
    // defaults for transformed JSON are complex; keep optional
    return `z.string().optional()`;
  }

  if (hasDefault) {
    const defaultValue = formatDefaultValue(v);
    return `${rule}.default(${defaultValue})`;
  }
  if (!isRequired) {
    return `${rule}.optional()`;
  }
  return rule;
}

function formatDefaultValue(v: EnvVariable): string {
  if (v.type === "number") return v.rawValue;
  if (v.type === "boolean") {
    return /^(true|1)$/i.test(v.rawValue) ? "true" : "false";
  }
  return JSON.stringify(v.rawValue);
}

function generateZod(vars: EnvVariable[]): string {
  const body = vars
    .map((v) => {
      const comment = v.description ? `\n  // ${v.description.replace(/\n/g, " ")}` : "";
      return `${comment}\n  ${v.key}: ${zodRuleFor(v)},`;
    })
    .join("\n");

  return `import { z } from "zod";

// Generated by EnvSmith.
// process.env values are always strings; numeric and boolean schemas coerce safely.

export const envSchema = z.object({${body}
});

export type Env = z.infer<typeof envSchema>;

export const env = envSchema.parse(process.env);
`;
}

function generateTsTypes(vars: EnvVariable[]): string {
  const lines = vars.map((v) => {
    const tsType =
      v.type === "number"
        ? "number"
        : v.type === "boolean"
          ? "boolean"
          : v.type === "json"
            ? "unknown"
            : "string";
    const opt = v.required && v.rawValue !== "" ? "" : "?";
    const comment = v.description ? ` /** ${v.description.replace(/\n/g, " ")} */` : "";
    return `${lines_()}${comment}\n  ${v.key}${opt}: ${tsType};`;
  });
  return `// Generated by EnvSmith

declare global {
  namespace NodeJS {
    interface ProcessEnv {
${lines.join("\n")}
    }
  }
}

export {};
`;
}

function lines_(): string {
  return "  ";
}

function generateJsonSchema(vars: EnvVariable[]): string {
  const props = vars.map((v) => {
    const base: Record<string, unknown> = { type: "string" };
    if (v.type === "number") {
      Object.assign(base, { type: "string", pattern: "^-?\\d+(\\.\\d+)?$" });
    }
    if (v.type === "boolean") {
      Object.assign(base, { type: "string", enum: ["true", "false"] });
    }
    if (v.description) base.description = v.description;
    return `    ${JSON.stringify(v.key)}: ${JSON.stringify(base)}`;
  });
  const required = vars.filter((v) => v.required && v.rawValue !== "").map((v) => JSON.stringify(v.key));

  return `{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Environment variables",
  "type": "object",
  "properties": {
${props.join(",\n")}
  },
  "required": [${required.join(", ")}]
}
`;
}

function generateDotenvValidation(vars: EnvVariable[]): string {
  const lines = vars.map((v) => {
    const kind =
      v.type === "number" ? "int" : v.type === "boolean" ? "bool" : v.type === "url" ? "url" : "string";
    const required = v.required && v.rawValue !== "" ? "required" : "optional";
    return `// ${v.key}: ${kind}, ${required}${v.description ? ` — ${v.description.replace(/\n/g, " ")}` : ""}`;
  });
  return `# Generated validation notes by EnvSmith
# Use with dotenvx or a custom validator.
${lines.join("\n")}
`;
}
